name: dynamic-qr

services:
  qr-api:
    image: qr-api
    container_name: qr-api
    build: api
    env_file:
      - ./.env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
      - ME_CONFIG_MONGODB_SERVER=${DB_HOST}
    expose:
      - "${API_PORT}"
    networks:
      - mongo-network
    depends_on:
      - mongodb

  qr-web:
    image: qr-web
    container_name: qr-web
    env_file:
      - ./.env
    build:
      context: web
      args:
        - API_URL=${API_URL}
      target: prod
    expose:
      - "80"

  mongodb:
    container_name: mongodb
    # if u have issue like `MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!`
    # use mongo:4.4.18 instead.
    image: mongo:4.4.18
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    command: mongod --port 27017
    expose:
      - "27017"
    networks:
      - mongo-network

networks:
  mongo-network:
    name: mongo-network
